version: 1.1.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
before_build:
  - nuget restore
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: MockHttpServer.*.nupkg
  name: NuGet Package
cache:
- packages -> **\packages.config